-- MySQL Script generated by MySQL Workbench
-- 03/27/17 18:17:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- Schema model2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema model2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `model2` ;

USE `model2` ;

-- -----------------------------------------------------
-- Table `model2`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model2`.`Question` ;

CREATE TABLE IF NOT EXISTS `model2`.`Question` (
  `idQuestion` INT NOT NULL,
  `questionDesc` VARCHAR(4000) NULL DEFAULT NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model2`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model2`.`Answer` ;

CREATE TABLE IF NOT EXISTS `model2`.`Answer` (
  `idAnswer` INT NOT NULL,
  `answerDesc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idAnswer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model2`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model2`.`Category` ;

CREATE TABLE IF NOT EXISTS `model2`.`Category` (
  `idCategory` INT NOT NULL,
  `categoryDesc` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model2`.`Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model2`.`Section` ;

CREATE TABLE IF NOT EXISTS `model2`.`Section` (
  `idSection` INT NOT NULL,
  `sectionDesc` VARCHAR(100) NULL DEFAULT NULL,
  `idCategory` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSection`),
  INDEX `ifc_idx` (`idCategory` ASC),
  CONSTRAINT `ifc`
    FOREIGN KEY (`idCategory`)
    REFERENCES `model2`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model2`.`Survey_Fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model2`.`Survey_Fact` ;

CREATE TABLE IF NOT EXISTS `model2`.`Survey_Fact` (
  `idSurvey_Fact` INT NOT NULL,
  `idQuestion` INT NULL DEFAULT NULL,
  `idAnswer` INT NULL DEFAULT NULL,
  `idSection` INT NULL DEFAULT NULL,
  `response_count` INT NULL DEFAULT NULL,
  `response_percentage` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idSurvey_Fact`),
  INDEX `fq1_idx` (`idQuestion` ASC),
  INDEX `fa1_idx` (`idAnswer` ASC),
  INDEX `fs1_idx` (`idSection` ASC),
  CONSTRAINT `fq1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `model2`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fa1`
    FOREIGN KEY (`idAnswer`)
    REFERENCES `model2`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fs1`
    FOREIGN KEY (`idSection`)
    REFERENCES `model2`.`Section` (`idSection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
