-- MySQL Script generated by MySQL Workbench
-- 03/26/17 19:27:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema model1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema model1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `model1` DEFAULT CHARACTER SET utf8 ;
USE `model1` ;

-- -----------------------------------------------------
-- Table `model1`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Question` ;

CREATE TABLE IF NOT EXISTS `model1`.`Question` (
  `idQuestion` INT NOT NULL,
  `questionDesc` NVARCHAR(4000) NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Gender` ;

CREATE TABLE IF NOT EXISTS `model1`.`Gender` (
  `idGender` INT NOT NULL,
  `genderDesc` VARCHAR(10) NULL,
  PRIMARY KEY (`idGender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Income`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Income` ;

CREATE TABLE IF NOT EXISTS `model1`.`Income` (
  `idIncome` INT NOT NULL,
  `incomeDesc` VARCHAR(50) NULL,
  PRIMARY KEY (`idIncome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Education` ;

CREATE TABLE IF NOT EXISTS `model1`.`Education` (
  `idEducation` INT NOT NULL,
  `educationDesc` VARCHAR(20) NULL,
  PRIMARY KEY (`idEducation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Age`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Age` ;

CREATE TABLE IF NOT EXISTS `model1`.`Age` (
  `idAge` INT NOT NULL,
  `ageDesc` VARCHAR(30) NULL,
  PRIMARY KEY (`idAge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Race_Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Race_Ethnicity` ;

CREATE TABLE IF NOT EXISTS `model1`.`Race_Ethnicity` (
  `idRace_Ethnicity` INT NOT NULL,
  `race_EthnicityDesc` VARCHAR(50) NULL,
  PRIMARY KEY (`idRace_Ethnicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Political_Party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Political_Party` ;

CREATE TABLE IF NOT EXISTS `model1`.`Political_Party` (
  `idPolitical_Party` INT NOT NULL,
  `political_PartyDesc` VARCHAR(20) NULL,
  PRIMARY KEY (`idPolitical_Party`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Region` ;

CREATE TABLE IF NOT EXISTS `model1`.`Region` (
  `idRegion` INT NOT NULL,
  `regionDesc` VARCHAR(20) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Answer` ;

CREATE TABLE IF NOT EXISTS `model1`.`Answer` (
  `idAnswer` INT NOT NULL,
  `answerDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnswer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Gender_Fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Gender_Fact` ;

CREATE TABLE IF NOT EXISTS `model1`.`Gender_Fact` (
  `idGender_Fact` INT NOT NULL,
  `idGender` INT NULL,
  `idQuestion` INT NULL,
  `idAnswer` INT NULL,
  `response_count` INT NULL,
  `response_percentage` VARCHAR(5) NULL,
  PRIMARY KEY (`idGender_Fact`),
  INDEX `q_gf1_idx` (`idQuestion` ASC),
  INDEX `gf2_idx` (`idAnswer` ASC),
  INDEX `gf3_idx` (`idGender` ASC),
  CONSTRAINT `gf1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `model1`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gf2`
    FOREIGN KEY (`idAnswer`)
    REFERENCES `model1`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gf3`
    FOREIGN KEY (`idGender`)
    REFERENCES `model1`.`Gender` (`idGender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model1`.`Age_Fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model1`.`Age_Fact` ;

CREATE TABLE IF NOT EXISTS `model1`.`Age_Fact` (
  `idAge_Fact` INT NOT NULL,
  `idAge` INT NULL,
  `idQuestion` INT NULL,
  `idAnswer` INT NULL,
  `response_count` INT NULL,
  `response_percentage` VARCHAR(5) NULL,
  PRIMARY KEY (`idAge_Fact`),
  INDEX `af1_idx` (`idAnswer` ASC),
  INDEX `af2_idx` (`idQuestion` ASC),
  INDEX `af3_idx` (`idAge` ASC),
  CONSTRAINT `af1`
    FOREIGN KEY (`idAnswer`)
    REFERENCES `model1`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `af2`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `model1`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `af3`
    FOREIGN KEY (`idAge`)
    REFERENCES `model1`.`Age` (`idAge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
